FROM alpine:edge

RUN --mount=type=cache,target=/var/cache/apk \
	apk add --no-cache \
	abseil-cpp-base \
	abseil-cpp-city \
	abseil-cpp-civil-time \
	abseil-cpp-cord \
	abseil-cpp-cord-internal \
	abseil-cpp-cordz-functions \
	abseil-cpp-cordz-handle \
	abseil-cpp-cordz-info \
	abseil-cpp-cordz-sample-token \
	abseil-cpp-crc-cord-state \
	abseil-cpp-crc-cpu-detect \
	abseil-cpp-crc-internal \
	abseil-cpp-crc32c \
	abseil-cpp-debugging-internal \
	abseil-cpp-decode-rust-punycode \
	abseil-cpp-demangle-internal \
	abseil-cpp-demangle-rust \
	abseil-cpp-dev \
	abseil-cpp-die-if-null \
	abseil-cpp-examine-stack \
	abseil-cpp-exception-safety-testing \
	abseil-cpp-exponential-biased \
	abseil-cpp-failure-signal-handler \
	abseil-cpp-flags-commandlineflag \
	abseil-cpp-flags-commandlineflag-internal \
	abseil-cpp-flags-config \
	abseil-cpp-flags-internal \
	abseil-cpp-flags-marshalling \
	abseil-cpp-flags-parse \
	abseil-cpp-flags-private-handle-accessor \
	abseil-cpp-flags-program-name \
	abseil-cpp-flags-reflection \
	abseil-cpp-flags-usage \
	abseil-cpp-flags-usage-internal \
	abseil-cpp-graphcycles-internal \
	abseil-cpp-hash \
	abseil-cpp-hash-generator-testing \
	abseil-cpp-hashtable-profiler \
	abseil-cpp-hashtablez-sampler \
	abseil-cpp-int128 \
	abseil-cpp-kernel-timeout-internal \
	abseil-cpp-leak-check \
	abseil-cpp-log-entry \
	abseil-cpp-log-flags \
	abseil-cpp-log-globals \
	abseil-cpp-log-initialize \
	abseil-cpp-log-internal-check-op \
	abseil-cpp-log-internal-conditions \
	abseil-cpp-log-internal-fnmatch \
	abseil-cpp-log-internal-format \
	abseil-cpp-log-internal-globals \
	abseil-cpp-log-internal-log-sink-set \
	abseil-cpp-log-internal-message \
	abseil-cpp-log-internal-nullguard \
	abseil-cpp-log-internal-proto \
	abseil-cpp-log-internal-structured-proto \
	abseil-cpp-log-internal-test-actions \
	abseil-cpp-log-internal-test-helpers \
	abseil-cpp-log-internal-test-matchers \
	abseil-cpp-log-severity \
	abseil-cpp-log-sink \
	abseil-cpp-malloc-internal \
	abseil-cpp-per-thread-sem-test-common \
	abseil-cpp-periodic-sampler \
	abseil-cpp-poison \
	abseil-cpp-pow10-helper \
	abseil-cpp-profile-builder \
	abseil-cpp-random-distributions \
	abseil-cpp-random-internal-distribution-test-util \
	abseil-cpp-random-internal-entropy-pool \
	abseil-cpp-random-internal-platform \
	abseil-cpp-random-internal-randen \
	abseil-cpp-random-internal-randen-hwaes \
	abseil-cpp-random-internal-randen-hwaes-impl \
	abseil-cpp-random-internal-randen-slow \
	abseil-cpp-random-internal-seed-material \
	abseil-cpp-random-seed-gen-exception \
	abseil-cpp-random-seed-sequences \
	abseil-cpp-raw-hash-set \
	abseil-cpp-raw-logging-internal \
	abseil-cpp-scoped-mock-log \
	abseil-cpp-scoped-set-env \
	abseil-cpp-spinlock-test-common \
	abseil-cpp-spinlock-wait \
	abseil-cpp-stack-consumption \
	abseil-cpp-stacktrace \
	abseil-cpp-status \
	abseil-cpp-status-matchers \
	abseil-cpp-statusor \
	abseil-cpp-str-format-internal \
	abseil-cpp-strerror \
	abseil-cpp-string-view \
	abseil-cpp-strings \
	abseil-cpp-strings-internal \
	abseil-cpp-symbolize \
	abseil-cpp-synchronization \
	abseil-cpp-test-instance-tracker \
	abseil-cpp-throw-delegate \
	abseil-cpp-time \
	abseil-cpp-time-internal-test-util \
	abseil-cpp-time-zone \
	abseil-cpp-tracing-internal \
	abseil-cpp-utf8-for-code-point \
	abseil-cpp-vlog-config-internal \
	acl-libs \
	alpine-baselayout \
	alpine-baselayout-data \
	alpine-keys \
	alpine-release \
	apk-tools \
	autoconf \
	automake \
	bash-dev \
	binutils \
	binutils-aarch64-none-elf \
	binutils-arm-none-eabi \
	binutils-avr \
	binutils-cross-embedded \
	binutils-dev \
	binutils-i386-elf \
	binutils-msp430-elf \
	binutils-or1k-elf \
	binutils-riscv-none-elf \
	binutils-x86_64-elf \
	binutils-xtensa-esp32-elf \
	binutils-xtensa-esp32s2-elf \
	binutils-xtensa-esp32s3-elf \
	binutils-xtensa-esp8266-elf \
	binutils-xtensa-none-elf \
	bison \
	blake3-dev \
	blake3-libs \
	boost1.84 \
	boost1.84-atomic \
	boost1.84-chrono \
	boost1.84-container \
	boost1.84-context \
	boost1.84-contract \
	boost1.84-coroutine \
	boost1.84-date_time \
	boost1.84-dev \
	boost1.84-fiber \
	boost1.84-filesystem \
	boost1.84-graph \
	boost1.84-iostreams \
	boost1.84-json \
	boost1.84-libs \
	boost1.84-locale \
	boost1.84-log \
	boost1.84-log_setup \
	boost1.84-math \
	boost1.84-nowide \
	boost1.84-prg_exec_monitor \
	boost1.84-program_options \
	boost1.84-python3 \
	boost1.84-random \
	boost1.84-regex \
	boost1.84-serialization \
	boost1.84-stacktrace_basic \
	boost1.84-stacktrace_noop \
	boost1.84-system \
	boost1.84-thread \
	boost1.84-timer \
	boost1.84-type_erasure \
	boost1.84-unit_test_framework \
	boost1.84-url \
	boost1.84-wave \
	boost1.84-wserialization \
	brotli \
	brotli-dev \
	brotli-libs \
	build-base \
	busybox \
	busybox-binsh \
	bzip2-dev \
	c-ares \
	c-ares-dev \
	ca-certificates-bundle \
	ccache \
	clang21 \
	clang21-ccache \
	clang21-dev \
	clang21-extra-tools \
	clang21-headers \
	clang21-libclang \
	clang21-libs \
	cmake \
	cmake-vim \
	cpupower \
	curl-dev \
	diffutils \
	eudev-libs \
	file \
	fio \
	flex \
	flex-dev \
	flex-libs \
	fortify-headers \
	fzf \
	fzf-vim \
	g++ \
	g++-aarch64-none-elf \
	g++-arm-none-eabi \
	g++-cross-embedded \
	g++-or1k-elf \
	g++-riscv-none-elf \
	gawk \
	gcc \
	gcc-aarch64-none-elf \
	gcc-arm-none-eabi \
	gcc-cross-embedded \
	gcc-gdb \
	gcc-i386-elf \
	gcc-msp430-elf \
	gcc-or1k-elf \
	gcc-riscv-none-elf \
	gcc-x86_64-elf \
	gcc-xtensa-esp32-elf \
	gcc-xtensa-esp32s2-elf \
	gcc-xtensa-esp32s3-elf \
	gcc-xtensa-esp8266-elf \
	gcc-xtensa-none-elf \
	gdb \
	gdbm \
	gettext \
	gettext-asprintf \
	gettext-dev \
	gettext-envsubst \
	gettext-libs \
	git \
	git-init-template \
	git-perl \
	gmock \
	gmp \
	gmp-dev \
	gtest \
	gtest-dev \
	highway-dev \
	hiredis \
	hwloc \
	hwloc-dev \
	hyperfine \
	icu \
	icu-data-en \
	icu-dev \
	icu-libs \
	isl26 \
	jansson \
	jemalloc \
	jemalloc-dev \
	json-c \
	judy \
	libaio \
	libapk \
	libarchive \
	libatomic \
	libbpf \
	libbsd \
	libbz2 \
	libcap2 \
	libcrypto3 \
	libcurl \
	libdebuginfod \
	libdw \
	libedit \
	libelf \
	libexpat \
	libffi \
	libffi-dev \
	libformw \
	libgcc \
	libgccjit \
	libgccjit-dev \
	libgmpxx \
	libgomp \
	libhistory \
	libhwy \
	libhwy_contrib \
	libhwy_test \
	libidn2 \
	libidn2-dev \
	libintl \
	liblksctp \
	libltdl \
	libmagic \
	libmd \
	libmenuw \
	libncurses++ \
	libncursesw \
	libnl3 \
	libomptarget \
	libomptarget-rtl \
	libomptarget-rtl-amdgpu \
	libomptarget-rtl-cuda \
	libpanelw \
	libpsl \
	libpsl-dev \
	libpsl-utils \
	libsodium \
	libsodium-dev \
	libssl3 \
	libstdc++ \
	libstdc++-dev \
	libtool \
	libtraceevent \
	libtraceevent-plugins \
	libunistring \
	libuv \
	libxml2 \
	libxml2-dev \
	libxml2-utils \
	libxxhash \
	libzmq \
	linux-headers \
	linux-tools-dev \
	linux-tools-usbip \
	lld21 \
	lld21-dev \
	lld21-libs \
	lldb \
	lldb-dev \
	llvm18-libs \
	llvm21 \
	llvm21-dev \
	llvm21-libs \
	llvm21-linker-tools \
	llvm21-test-utils \
	llvm21-test-utils-pyc \
	ltrace \
	lz4-libs \
	m4 \
	make \
	meson \
	meson-pyc \
	meson-vim \
	mimalloc2 \
	mimalloc2-debug \
	mimalloc2-dev \
	mimalloc2-insecure \
	mingw-w64-binutils \
	mingw-w64-crt \
	mingw-w64-gcc \
	mingw-w64-gcc-ccache \
	mingw-w64-headers \
	mingw-w64-winpthreads \
	mold \
	mpc1 \
	mpdecimal \
	mpfr4 \
	musl \
	musl-dbg \
	musl-dev \
	musl-fts \
	musl-obstack \
	musl-utils \
	ncurses-dev \
	ncurses-terminfo-base \
	newlib-aarch64-none-elf \
	newlib-arm-none-eabi \
	newlib-or1k-elf \
	newlib-riscv-none-elf \
	nghttp2-dev \
	nghttp2-libs \
	nghttp3 \
	nghttp3-dev \
	numactl \
	numactl-dev \
	onetbb \
	onetbb-dev \
	openmp \
	openmp-bitcode \
	openmp-dev \
	openssl-dev \
	pahole \
	patch \
	pciutils-dev \
	pciutils-libs \
	pcre2 \
	perf \
	perl \
	perl-error \
	perl-git \
	pkgconf \
	pkgconf-dev \
	pyc \
	python3 \
	python3-dev \
	python3-pyc \
	python3-pycache-pyc0 \
	readline \
	readline-dev \
	rhash-libs \
	ripgrep \
	rust \
	samurai \
	scanelf \
	scudo-malloc \
	sed \
	simde-dev \
	simdjson \
	simdjson-dev \
	simdutf \
	simdutf-dev \
	slang \
	sqlite \
	sqlite-dev \
	sqlite-libs \
	ssl_client \
	strace \
	stress-ng \
	valgrind-dev \
	vim \
	vim-common \
	wget \
	xtensa-dynconfig-esp32 \
	xtensa-dynconfig-esp32s2 \
	xtensa-dynconfig-esp32s3 \
	xtensa-dynconfig-esp8266 \
	xxd \
	xxhash-dev \
	xz \
	xz-dev \
	xz-libs \
	zeromq-dev \
	zlib \
	zlib-dev \
	zstd \
	zstd-dev \
	zstd-libs

CMD [ "/bin/bash" ]
